; Exercise 1.14 Draw the tree illustrating the process generated by the
; count-change procedure of section 1.2.2 in making change for 11 cents. What
; are the orders of growth of the sapce and number of steps used by this process
; as the amount to be changed increases?

; Apparently making change for any amount a for n kinds of coins can be reduced
; to the following:
; 1. the number of ways to change amount a using all but the first kind of coin,
; plus
; 2. the number of ways to change amount a-d using all n kinds of coins, where
; d is the denomination of the first kind of coin.
;
; Recursively defined boundary conditions:
; 1. If a is exactly 0, that counts as 1 way to make change.
; 2. If a is less than 0, that counts as 0 ways to make change.
; 3. If n is 0, that counts as 0 ways to make change.
; The order of the coins in the first-denomination function does not matter

(define (count-change amount)
    (cc amount 5)
(define (cc amount kinds-of-coins))
    (cond ((= amount 0) 1)
          ((or (< amount 0) (= kinds-of-coins 0)) 0)
          (else (+ (cc amount
                       (- kinds-of-coins 1))
                   (cc (- amount
                          (first-denomination kinds-of-coins))
                       kinds-of-coins)))))
(define (first-denomination kinds-of-coins)
  (cond ((= kinds-of-coins 1) 1)
        ((= kinds-of-coins 2) 5)
        ((= kinds-of-coins 3) 10)
        ((= kinds-of-coins 4) 25)
        ((= kinds-of-coins 5) 50)))

; Tree for count-change for 11 cents
; (count-change 11)
;      |
; (cc 11 5)
;      |
; (cc 11 4) ---- (cc -39 5)
;      |              |
;      |              0
;      |
; (cc 11 3) ---- (cc -14 4)
;      |              |
;      |              0
;      |
; (cc 11 2) ---------------------------------------------- (cc 1 3)
;      |                                                     |
;      |                                                  (cc 1 2) ---- (cc -9 3)
; (cc 11 1) ---------- (cc 6 2)                              |             | 
;      |                   |                                 |             0
;      |                   |                                 |
;      |                (cc 6 1) ---- (cc 1 2)           (cc 1 1) ---- (cc -4 2)
;      |                   |           |                     |             |
;      |  (cc 5 1) ---- (cc 6 0)      (cc 1 1) --- (cc -4 2) |             0
;      |     |             |           |            |        |
;      |     |             0           |            0     (cc 1 0) ---- (cc 0 1)
;      |     |                         |                     |             |
;      |  (cc 5 0) ---- (cc 4 1)      (cc 1 0) --- (cc 0 1)  0             1
;      |     |             |           |            |
;      |     0             |           0            1
;      |                   |
;      |                (cc 4 0) ---- (cc 3 1)
;      |                   |             |
;      |                   0             |
;      |                              (cc 3 0) ---- (cc 2 1)
;      |                                 |              |
;      |                                 0              |
;      |                                            (cc 2 0) ---- (cc 1 1)
;      |                                                |            |
; (cc 11 0) ---- (cc 10 1)                              0            |
;      |             |                                               |
;      0             |                              (cc 0 1) ---- (cc 1 0)
;                    |                                  |            |
;                (cc 10 0) ---- (cc 9 1)                1            0
;                    |              |
;                    0              |
;                               (cc 9 0) ---- (cc 8 1)
;                                   |             |
;                                   0         (cc 8 0) ---- (cc 7 1)
;                                                 |             |
;                                                 0             |
;                                                               |
;                                             (cc 6 1) ---- (cc 7 0)
;                                                 |             |
;                               (cc 5 1) ---- (cc 6 0)          0
;                                   |             |
;                (cc 4 1) ----  (cc 5 0)          0
;                   |               |
; (cc 3 1) ----  (cc 4 0)           0
;    |              |
;    |              0
;    |
; (cc 3 0) ---- (cc 2 1)
;    |              |
;    0          (cc 2 0) --- (cc 1 1)
;                   |           |
;                   0        (cc 1 0) ---- (cc 0 1)
;                               |              |
;                               0              1
;
; What is the growth of space and operations per change amount?
; This is difficult and I am not sure how to figure it out!
