; Exercise 1.15. The sine of an angle(specified in radians) can be computer by 
; making use of the approximation sin x ~ x if x is sufficiently small, and the
; trig identity sin r = 3 sin r/3 - 4 sin^3 r/3
; to reduce the size of the argument to sin. (For purposes of this exercise an 
; angle is considered "sufficiently small" if its magnitude is not greater than
; 0.1 radians.) These ideas are incorporated in the following procedures:
;

(define (cube x) (* x x x))
(define (p x) (- (* 3 x) (* 4 (cube x))))
(define (sine angle)
  (if (not (> (abs angle) 0.1))
      angle
      (p (sine (/ angle 3.0)))))

; How many times is the procedure p applied when (sine 12.15) is evaluated?

; (sine 12.15)
; (p (sine 4.05))
;    (p (sine 1.35))
;       (p (sine 0.45))
;          (p (sine 0.15))
;             (p (sine 0.05))
;
;It is called 5 times
;
; What is the order of growth in space and number of steps (as a function of a)
; used by the process generated by the sine procedure when (sine a) is
; evaluated?
;
; Angle a is divided by 3 each time p is called. Therefore the procedure will
; grow according to how many powers of 3 are within a. Using the change of
; base formula logb(x) = loga(x)/loga(b) we can show that the O(sine a) is
; O(log(a)):
; more specifically O(sine a) = ceiling(log(a/0.1)/log(3))
